### ISSUE TITLE
blank page after starting cryptpad

### ISSUE THREAD

**Issue by Venice-89** [xwiki-labs/cryptpad#246]
Hi,

I installed cryptpad on my Ubuntu 18.04 Server, like you descriped it here on github.
Now I see the cryptpad page, but If I click on "Rhich Text Document" I get only a blank page.

What can cause this issue?

Output of node server:
/opt/cryptpad # node server
loading task scheduler

[2018-06-06T16:35:38.229Z] server available http://[::]:3000
Cryptpad is customizable, see customize.dist/readme.md for details
loading rpc module...

**Comment by Venice-89** [comment]
ok found the problem... I tried to use cryptad via <Server-IP>:3000 that seems not to work via <my-domain.de>:3000 it works

**Comment by ansuz** [comment]
This is due to the [CSP Headers](https://github.com/xwiki-labs/cryptpad/wiki/CSP-headers) defined in your configuration file. We assume that a CryptPad instance will only be deployed on one domain, and forbid any other domain from interacting with user content.

**Comment by coolblock** [comment]
Currently, I have the same problem, blank. I bring it up using the server IP:3000 and the returned page is blank. I changed localhost in the config file and that did not help. Do I have to have a domain name pointing to the ip rather than the ip?

I don't understand what "ok found the problem... I tried to use cryptad via Server-IP:3000 that seems not to work via <my-domain.de>:3000 it works" refers to.

**Comment by dartie** [comment]
Hi, please what's the resolution of this?

**Comment by ansuz** [comment]
A white screen means your instance is incorrectly configured and this usually relates to our use of CSP headers, as mentioned in my comment above.

See your browser console. It should tell you why certain content or scripts are being blocked.

If you are running CryptPad 4.4.0 you should be able to review your instances `/checkup/` page to see the results of an automated diagnosis of your its configuration.

**Comment by bbbart** [comment]
I just successfully installed a new instance of version 4.13.0. Everything seems to work just fine and I'm really happy with the product.

However... I do get a blank page when trying to access the `/checkup/` page, with no apparent errors in the nginx log file. I do get a CSP-error in my browser's console, but even after removing the CSP-headers completely (and thus avoiding the script-src error), it still shows me a blank page.

Nothing major for now, but I still thought I'd let you guys know.

**Comment by ansuz** [comment]
> I just successfully installed a new instance of version 4.13.0. Everything seems to work just fine and I'm really happy with the product.
> 
> However... I do get a blank page when trying to access the `/checkup/` page, with no apparent errors in the nginx log file. I do get a CSP-error in my browser's console, but even after removing the CSP-headers completely (and thus avoiding the script-src error), it still shows me a blank page.
> 
> Nothing major for now, but I still thought I'd let you guys know.

Any errors are more liky to appear in the browser's console than in the NGINX log file, since the page content is rendered on the client rather than the server.

We try to make this page as resilient as possible, which is challenging, because the server has to be working to some degree in order for its tests to run.

I'm aware of one bug from `4.13.0` where one test attempted to parse CSP headers that didn't exist. Trying to parse the `null` value as a string resulted in an unhandled error. `4.14.0` now handles that case, but I don't think that was your error as you would have still seen _something_ on the page even though the tests would have never finished running.

Another possibility is that you didn't run `bower install` or `bower update`. The checkup page requires some client-side dependencies to work. I've just added an extra script which handles this case and displays an error when a dependency fails to load.

![image](https://user-images.githubusercontent.com/1264398/161502579-df97280c-825c-4729-93c8-93114015f132.png)

I plan to tag `4.14.0` later today, so this case will be handled going forward.

If none of these fixes help then we'll need more information. If you figure out what's preventing the page from loading we can see about making it easier for admins to identify the problem in the future.

**Comment by ansuz** [comment]
From your screenshot I can see that you're loading it from `/checkup` rather than `/checkup/`. The configuration file we provide includes [rules to rewrite the URL to include the trailing slash](https://github.com/xwiki-labs/cryptpad/blob/main/docs/example.nginx.conf#L237-L242) for most of the platform's pages, but I see that `checkup` is missing from this list. [This commit](https://github.com/xwiki-labs/cryptpad/commit/01b6dd539bfc07fce697b87fa4202657ebc91d3e) adds it to the list of pages where the trailing slash should be added. 

If you load `/checkup/` (with the trailing slash) you should see that it loads as expected.

Now that I'm looking at your checkup page I see some symptoms of a bug that was introduced today :sweat_smile: which is fixed in [this commit](https://github.com/xwiki-labs/cryptpad/commit/6bc1c24608626dbe74b2295d4e9592f681f6c428).

**Comment by bbbart** [comment]
Ahaa! Great to see progress is being made so swiftly. I updated our nginx config (by the way, I believe you made a small mistake in the git commit message there - just a detail of course).

Anyway, I can start tinkering with our setup now that I have a detailed checkup report, great!

(`npm install` still fails on the `git ls-remote` however, is this a solvable from my end?)

**Comment by ansuz** [comment]
> (`npm install` still fails on the `git ls-remote` however, is this a solvable from my end?)

https://stackoverflow.com/questions/1722807/how-to-convert-git-urls-to-http-urls

**Comment by bbbart** [comment]
hm, that's interesting. it doesn't seem to do much for me however. :-(

```
cryptpad@vm01 ~ % git config --global url.https://github.com/.insteadOf ssh://git@github.com:
cryptpad@vm01 ~ % npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/dchest/tweetnacl-js.git
npm ERR!
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     /opt/cryptpad/.npm/_logs/2022-04-06T17_05_19_403Z-debug.log
cryptpad@vm01 ~ %
```

but I'm thinking this is not such a big deal, is it?

Strange though that this is only hapenning now. The initial `npm install` after my first clone of the cryptpad repository worked just fine.
