### ISSUE TITLE
drive stuck at Failed to execute ‘postMessage’ on ‘DOMWindow’

### ISSUE THREAD

**Issue by hapee** [xwiki-labs/cryptpad#882]
I know that this has to do with The target origin provided (‘http://localhost:3000’) does not match the recipient window’s origin (‘my domain’).
But I followed all the instruction copied the last nginx example file and nothing helps, I do not come beyond this point, so need some support here.

**Comment by ansuz** [comment]
Hi,

It sounds like you're describing a common domain configuration issue which is addressed in our [documentation](https://docs.cryptpad.fr/en/admin_guide/installation.html#admin-domain-config). If you use the _checkup_ page which is described [here](https://docs.cryptpad.fr/en/admin_guide/admin_panel.html#network) it should give fairly detailed information about what configuration is wrong and how to correct it.

Beyond that, you can ask for community support in our [#instance-admins matrix channel ](https://matrix.to/#/#cryptpad-admins:matrix.xwiki.com).

**Comment by hapee** [comment]
Thanks @ansuz for your reply, I understand and I would not create a ticket if I had not tried everything which I did, I am running this Cryptpad for 5 year now and it always worked until the upgrade to 4.13.0. I triplechecked the documentation and everything is correct as far as I can see.
I will check again and contact the matrix channel in case it is still not working at some point.

**Comment by ansuz** [comment]
It's most likely the case that your server was always configured incorrectly. The change with 4.13.0 is that the client detects these errors and refuses to operate under unsafe or unexpected conditions. Your instance's checkup page should confirm this.

**Comment by jarforce** [comment]
we faced the same with  4.13.0 on test:
 error show: 

```
https://domain.com/ was served with incorrect Content-Security-Policy headers.
A value of "'self' blob: https://doc.domain.com https://pada.domain.com wss://doc.domain.com" was expected for the connect-src directive.

```
and nginx config shown: 

```

<html>
<body>
<!--StartFragment-->

Failed test number | 26
-- | --
Returned value | { 
 "default-src": "'none'",  
"child-src": "https://doc.domain.com", 
 "worker-src": "'self'",  
"media-src": "blob:",  
"style-src": "'unsafe-inline' 'self' https://doc.domain.com",  
"script-src": "'self' resource: https://doc.domain.com", 
 "connect-src": "'self' blob: https://doc.domain.com https://pada.domain.com wss://api.domain.com", 
 "font-src": "'self' data: https://doc.domain.com",  
"img-src": "'self' data: blob: https://doc.domain.com",  
"frame-src": "'self' https://pada.domain.com blob:" }

<!--EndFragment-->
</body>
</html>

```

Can not realized which was wrong,

**Comment by ansuz** [comment]
I'm going to close this as it doesn't seem to be a bug in the software.
